POST http://localhost:3001/api/users/signin
Content-Type: application/json

{
    "email": "meep@g",
    "password": "1"
}
###
GET http://localhost:3001/api/users/6491b0a3b24f563e61a8bba7
###
POST http://localhost:3001/api/users/signup
Content-Type: application/json

{
    "name": "Meep",
    "email": "meep@gmail.com",
    "password": "goose"
}
###
GET http://localhost:3001/api/orders/64946c3a8f87142c48545212
